### ISSUE TITLE
Zone quadrillée à 2 dimensions

### ISSUE THREAD

**Issue by mdevoldere** [Nthouvenot/2048_CRT#3]
Implémenter une classe représentant une zone quadrillée à 2 dimensions.
Une zone est définie par une largeur (nombre de colonnes) et une hauteur (nombre de lignes).
Dans cette zone, il sera possible d'y ajouter des objets (1 par "case"). Le type d'objet accepté dans la zone (un seul type par zone) est défini dans le constructeur.

**Comment by LaetitiaCR** [comment]
j'ai réalisé 3 class 
Point 
ZoneQuadrillee qui hérite de Point 
and Number qui hérite de ZoneQuadrillee
Merci de me donner ton avis.

**Comment by Nthouvenot** [comment]
D'accord je vais essayé de regarder ton code aujourd'hui ( 24/06/20 ), et je te fais mon retour.

**Comment by Nthouvenot** [comment]
Des choses sont a revoir notamment le constructeur de la classe ZoneQuadrille qui devrait ne rien retourné et faire des typeof  et si pas du bon type on met une valeur par défaut + respect de l'encapsulation.
